### PR TITLE
Support open files limit on qpidd too

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@ekohl can I get a review when you get a chance? Taking over the PR that Stephen was working on per Erics instructions since its a blocker for downstream.

**Comment by chris1984** [comment]
Tests were green on my laptop before submitting:

Finished in 8.89 seconds (files took 2.86 seconds to load)
125 examples, 0 failures

chrobert@vault111:~/Dropbox/git/puppet-qpid$ git branch -v
  master     dae5c04 Allow puppetlabs-concat 4.0.0 (#60)
* open_files ffea726 Support open files limit on qpidd too

**Comment by stbenjam** [comment]
FWIW, if you take a PR from someone else you should give them a chance and ping them, and then if you do take it over, cherry-pick the commit and leave authorship intact.

**Comment by chris1984** [comment]
@stbenjam sure i was not trying to steal the pr just doing what @ehelms suggested. I want to make sure you get the credit for it.

**Comment by ekohl** [comment]
Tests fail because facter 2.5 was released and the facterdb gem has no facts for 2.5. We need a modulesync run to pin on 2.4 facts.

**Comment by chris1984** [comment]
@ekohl i updated the other pr that @stbenjam was working on to see if he wanted to pick up that one, either way if its his or this one I would like for him to get credit as its his code.

**Comment by chris1984** [comment]
Did a cherry pick of this PR so Stephen gets authorship and going to open a new one... Closing this one out so its done the correct way.

**Pull request closed without merging**
