### PR TITLE
Pin rspec on ruby 1.8.7

### PR DESCRIPTION
**Pull request by stbenjam**
It was already here, but making it consistent w/ the others

### CODE REVIEW

**Comment by ehelms** [comment]
APT

**Comment by stbenjam** [comment]
Also renamed subject -> resource due to https://github.com/rodjek/rspec-puppet/issues/235

**Comment by ehelms** [comment]
APT

**Comment by ehelms** [comment]
@stbenjam seems it didn't like your catalog change

**Comment by ehelms** [comment]
@stbenjam is this still needed after the modulesync updates?

**Comment by stbenjam** [comment]
Nope

**Pull request closed without merging**
