### PR TITLE
Configure performance tuning settings for qpid

### PR DESCRIPTION
**Pull request by stbenjam**
When you have significant numbers of qpid or qdrouterd connections,
you need to set max-connections for qpid, and increase the number
of open files for qdrouterd.

### CODE REVIEW

**Comment by stbenjam** [comment]
Note: this pulls in https://github.com/camptocamp/puppet-systemd to manage the systemd limits file.  It's not a big module and might come in handy later.  We could resort to managing the file manually if you'd prefer not to bring it in.

**Comment by ehelms** [comment]
The only question I would have is whether you were wanting to backport this to any prior release that supported EL6? That would be the only limiting factor to using the systemd module (or just creating a separate patch for a backport).

**Comment by stbenjam** [comment]
I don't think so, the module officially dropped el6 although it still probably works with it anyway, there's a `$::systemd` fact which says if it's a systemd distro and I do check that before setting the systemd-related setting.

**Comment by stbenjam** [comment]
Although maybe we want to cherry pick the max-connections qpid setting to el6, I'll break this into 2 issues, to keep the systemd stuff separate.

**Comment by stbenjam** [comment]
@ehelms I broke it into 2 commits, 32ef591 specifically addresses only the BZ to make it easier to cherry-pick.  e094084 has the systemd changes.

**Comment by ehelms** [comment]
Do we need to consider finding a way to move `puppet-qpid` to the top of the installer or is the idea to leave this tuning for hiera config?

**Comment by stbenjam** [comment]
Hiera for the moment, because of the cert generation and other interdependencies moving it and pulp to the top level is still a little challenging

**Comment by stbenjam** [comment]
Ready for another look

**Comment by ekohl** [comment]
I'm a bit hesitant in adding another dependency, but camptocamp does write good modules. The biggest risk I see is that they'll drop puppet 3 support earlier than we want to. Otherwise it looks good.

**Pull request merged**
