### PR TITLE
add possibility to overwrite the installation packages

### PR DESCRIPTION
**Pull request by daniel-alt**

### CODE REVIEW

**Comment by stbenjam** [comment]
Thanks @daniel-alt, looks good to me... 

I want to test this though along with the changes we're making over in  https://github.com/Katello/puppet-qpid/pull/12, will try to do it next week.

**Comment by stbenjam** [comment]
@daniel-alt This needs a rebase - Or...

@bechtoldt can you submit a PR to the katello-qpid module directly? Sorry, totally forgot about your PR when I merged #12.... so many puppet module PR's this week.

Whoever's first wins :-)

**Comment by bechtoldt** [comment]
@daniel-alt this PR can be closed, see #14

**Comment by daniel-alt** [comment]
Ok

**Pull request closed without merging**
